import { GoogleGenerativeAI } from '@google/generative-ai';
import dotenv from 'dotenv';

dotenv.config();

// Initialize the Google Generative AI with the API key from the environment
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

/**
 * Basic service to interact with Gemini AI
 * You can pass a prompt to get a response generated by the AI
 */
export const geminiService = async (prompt, modelName = 'gemini-1.5-flash') => {
    try {
        // For text-only input, use the gemini-1.5-flash model
        const model = genAI.getGenerativeModel({ model: modelName });

        const result = await model.generateContent(prompt);
        const response = result.response;
        return response.text();
    } catch (error) {
        console.error('Error generating content with Gemini:', error);
        throw new Error('Failed to generate response from Gemini AI');
    }
};
